import {
  Activity,
  Anchor,
  Atom,
  Award,
  BadgeCheck,
  BookOpen,
  Bone,
  Bike,
  Boxes,
  Cake,
  CalendarCheck,
  CalendarDays,
  Clock,
  Compass,
  Crown,
  Dumbbell,
  Flag,
  Flame,
  Gauge,
  Gem,
  Grip,
  Hammer,
  Hourglass,
  Infinity as InfinityIcon,
  Layers,
  Magnet,
  Medal,
  Milestone,
  Moon,
  Mountain,
  Orbit,
  Package,
  PartyPopper,
  Plane,
  Radar,
  Repeat,
  Rocket,
  Ruler,
  Scale,
  Ship,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Sword,
  Swords,
  Target,
  Telescope,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  Weight,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react-native';
import type { ProfileStats } from './stats';

/**
 * The achievement catalogue.
 *
 * Rules this list is built to:
 *
 * 1. Every badge has a PRECISE, stated criterion evaluated against the user's
 *    real log. Nothing is awarded for opening the app, and nothing is awarded
 *    on the first session — an achievement nobody can fail is decoration, not
 *    an achievement.
 * 2. Every criterion is countable, so a locked badge can show how close it is
 *    rather than just taunting.
 * 3. Rarity is a claim about difficulty, not a colour. Legendary tiers are
 *    genuinely years of training away for most lifters.
 */

export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

export type BadgeCategory = 'consistency' | 'volume' | 'strength' | 'variety' | 'milestone';

export type BadgeUnit = 'count' | 'kg' | 'hours' | 'ratio';

export type BadgeDef = {
  id: string;
  name: string;
  category: BadgeCategory;
  rarity: Rarity;
  icon: LucideIcon;
  /** Shown while locked. Must state the exact bar. */
  criterion: string;
  /** Shown when earned. */
  blurb: string;
  unit: BadgeUnit;
  /** The bar. A function when it depends on the catalogue rather than a constant. */
  target: number | ((s: ProfileStats) => number);
  /** Current standing against the bar. */
  measure: (s: ProfileStats) => number;
};

export const RARITY_ORDER: Record<Rarity, number> = {
  common: 0,
  uncommon: 1,
  rare: 2,
  epic: 3,
  legendary: 4,
};

export const RARITY_LABEL: Record<Rarity, string> = {
  common: 'Common',
  uncommon: 'Uncommon',
  rare: 'Rare',
  epic: 'Epic',
  legendary: 'Legendary',
};

export const CATEGORY_LABEL: Record<BadgeCategory, string> = {
  consistency: 'Consistency',
  volume: 'Volume',
  strength: 'Strength',
  variety: 'Variety',
  milestone: 'Milestones',
};

export const BADGE_CATEGORIES: BadgeCategory[] = [
  'consistency',
  'volume',
  'strength',
  'variety',
  'milestone',
];

const def = (b: BadgeDef): BadgeDef => b;

export const BADGES: readonly BadgeDef[] = [
  // ---------------------------------------------------------------- consistency
  def({
    id: 'workouts-10',
    name: 'Getting Serious',
    category: 'consistency',
    rarity: 'common',
    icon: Dumbbell,
    criterion: 'Finish 10 workouts',
    blurb: 'Ten sessions in. Past the point where most people stop.',
    unit: 'count',
    target: 10,
    measure: (s) => s.workouts,
  }),
  def({
    id: 'workouts-50',
    name: 'Regular',
    category: 'consistency',
    rarity: 'uncommon',
    icon: BadgeCheck,
    criterion: 'Finish 50 workouts',
    blurb: 'Fifty sessions. This is a habit now, not an experiment.',
    unit: 'count',
    target: 50,
    measure: (s) => s.workouts,
  }),
  def({
    id: 'workouts-100',
    name: 'Century',
    category: 'consistency',
    rarity: 'rare',
    icon: Trophy,
    criterion: 'Finish 100 workouts',
    blurb: 'One hundred logged sessions.',
    unit: 'count',
    target: 100,
    measure: (s) => s.workouts,
  }),
  def({
    id: 'workouts-250',
    name: 'Quarter Thousand',
    category: 'consistency',
    rarity: 'epic',
    icon: Award,
    criterion: 'Finish 250 workouts',
    blurb: 'Two hundred and fifty sessions. Years of showing up.',
    unit: 'count',
    target: 250,
    measure: (s) => s.workouts,
  }),
  def({
    id: 'workouts-500',
    name: 'Five Hundred',
    category: 'consistency',
    rarity: 'legendary',
    icon: Crown,
    criterion: 'Finish 500 workouts',
    blurb: 'Five hundred sessions. Very few logs ever get here.',
    unit: 'count',
    target: 500,
    measure: (s) => s.workouts,
  }),
  def({
    id: 'weeks-4',
    name: 'Four-Week Rhythm',
    category: 'consistency',
    rarity: 'common',
    icon: Repeat,
    criterion: 'Hit your weekly session target 4 weeks running',
    blurb: 'A month of weeks that all hit your own target.',
    unit: 'count',
    target: 4,
    measure: (s) => s.longestWeekStreak,
  }),
  def({
    id: 'weeks-13',
    name: 'A Full Quarter',
    category: 'consistency',
    rarity: 'uncommon',
    icon: CalendarCheck,
    criterion: 'Hit your weekly target 13 weeks running',
    blurb: 'Thirteen straight weeks on target. A whole training block.',
    unit: 'count',
    target: 13,
    measure: (s) => s.longestWeekStreak,
  }),
  def({
    id: 'weeks-26',
    name: 'Half a Year',
    category: 'consistency',
    rarity: 'rare',
    icon: CalendarDays,
    criterion: 'Hit your weekly target 26 weeks running',
    blurb: 'Six months without a missed week.',
    unit: 'count',
    target: 26,
    measure: (s) => s.longestWeekStreak,
  }),
  def({
    id: 'weeks-52',
    name: 'Year-Round',
    category: 'consistency',
    rarity: 'legendary',
    icon: InfinityIcon,
    criterion: 'Hit your weekly target 52 weeks running',
    blurb: 'A full year of weeks, every one of them on target.',
    unit: 'count',
    target: 52,
    measure: (s) => s.longestWeekStreak,
  }),
  def({
    id: 'months-12',
    name: 'Twelve Months',
    category: 'consistency',
    rarity: 'rare',
    icon: Milestone,
    criterion: 'Train in 12 different calendar months',
    blurb: 'Twelve separate months with training in them.',
    unit: 'count',
    target: 12,
    measure: (s) => s.trainingMonths,
  }),
  def({
    id: 'comeback-1',
    name: 'Back On It',
    category: 'consistency',
    rarity: 'common',
    icon: Rocket,
    criterion: 'Return to training after a break of two weeks or more',
    blurb: 'You stopped, and then you came back. That is the actual skill.',
    unit: 'count',
    target: 1,
    measure: (s) => s.comebacks,
  }),
  def({
    id: 'comeback-3',
    name: 'Unbreakable',
    category: 'consistency',
    rarity: 'uncommon',
    icon: Shield,
    criterion: 'Come back from a two-week break three separate times',
    blurb: 'Three restarts. Nobody trains forever without stopping.',
    unit: 'count',
    target: 3,
    measure: (s) => s.comebacks,
  }),
  def({
    id: 'early-20',
    name: 'Early Bird',
    category: 'consistency',
    rarity: 'rare',
    icon: Sunrise,
    criterion: 'Start 20 sessions before 06:30',
    blurb: 'Twenty sessions started before half six.',
    unit: 'count',
    target: 20,
    measure: (s) => s.earlySessions,
  }),
  def({
    id: 'late-20',
    name: 'Night Shift',
    category: 'consistency',
    rarity: 'rare',
    icon: Moon,
    criterion: 'Start 20 sessions after 21:00',
    blurb: 'Twenty late sessions. The gym was empty and you were not.',
    unit: 'count',
    target: 20,
    measure: (s) => s.lateSessions,
  }),
  def({
    id: 'weekend-40',
    name: 'Weekend Warrior',
    category: 'consistency',
    rarity: 'uncommon',
    icon: Sun,
    criterion: 'Train on 40 weekend days',
    blurb: 'Forty Saturdays and Sundays spent under a bar.',
    unit: 'count',
    target: 40,
    measure: (s) => s.weekendSessions,
  }),
  def({
    id: 'days-100',
    name: 'Hundred Days',
    category: 'consistency',
    rarity: 'rare',
    icon: Flame,
    criterion: 'Train on 100 different days',
    blurb: 'One hundred separate days with work in them.',
    unit: 'count',
    target: 100,
    measure: (s) => s.trainingDays,
  }),
  def({
    id: 'double-day',
    name: 'Twice in a Day',
    category: 'consistency',
    rarity: 'uncommon',
    icon: Layers,
    criterion: 'Log two sessions in one day',
    blurb: 'Two sessions, one day.',
    unit: 'count',
    target: 2,
    measure: (s) => s.maxSessionsInOneDay,
  }),
  def({
    id: 'month-20',
    name: 'Heavy Month',
    category: 'consistency',
    rarity: 'rare',
    icon: Zap,
    criterion: 'Log 20 sessions in one calendar month',
    blurb: 'Twenty sessions inside a single month.',
    unit: 'count',
    target: 20,
    measure: (s) => s.bestMonthSessions,
  }),
  def({
    id: 'week-6',
    name: 'Six in Seven',
    category: 'consistency',
    rarity: 'uncommon',
    icon: Activity,
    criterion: 'Log 6 sessions in one week',
    blurb: 'Six sessions in seven days.',
    unit: 'count',
    target: 6,
    measure: (s) => s.bestWeekSessions,
  }),

  // --------------------------------------------------------------------- volume
  def({
    id: 'volume-10k',
    name: 'Ten Tonnes',
    category: 'volume',
    rarity: 'common',
    icon: Package,
    criterion: 'Move 10,000 kg in total',
    blurb: 'Ten tonnes moved.',
    unit: 'kg',
    target: 10_000,
    measure: (s) => s.volumeKg,
  }),
  def({
    id: 'volume-100k',
    name: 'Hundred Tonnes',
    category: 'volume',
    rarity: 'uncommon',
    icon: Truck,
    criterion: 'Move 100,000 kg in total',
    blurb: 'A hundred tonnes. About four loaded articulated lorries.',
    unit: 'kg',
    target: 100_000,
    measure: (s) => s.volumeKg,
  }),
  def({
    id: 'volume-500k',
    name: 'Half a Million',
    category: 'volume',
    rarity: 'rare',
    icon: Ship,
    criterion: 'Move 500,000 kg in total',
    blurb: 'Half a million kilograms through your hands.',
    unit: 'kg',
    target: 500_000,
    measure: (s) => s.volumeKg,
  }),
  def({
    id: 'volume-1m',
    name: 'Million Kilo Club',
    category: 'volume',
    rarity: 'epic',
    icon: Plane,
    criterion: 'Move 1,000,000 kg in total',
    blurb: 'One million kilograms. Roughly two loaded 747s.',
    unit: 'kg',
    target: 1_000_000,
    measure: (s) => s.volumeKg,
  }),
  def({
    id: 'volume-5m',
    name: 'Five Million',
    category: 'volume',
    rarity: 'legendary',
    icon: Mountain,
    criterion: 'Move 5,000,000 kg in total',
    blurb: 'Five million kilograms. A decade of serious training.',
    unit: 'kg',
    target: 5_000_000,
    measure: (s) => s.volumeKg,
  }),
  def({
    id: 'session-15k',
    name: 'Big Session',
    category: 'volume',
    rarity: 'uncommon',
    icon: Hammer,
    criterion: 'Move 15,000 kg in a single session',
    blurb: 'Fifteen tonnes in one sitting.',
    unit: 'kg',
    target: 15_000,
    measure: (s) => s.biggestSessionKg,
  }),
  def({
    id: 'session-25k',
    name: 'Monster Session',
    category: 'volume',
    rarity: 'rare',
    icon: Swords,
    criterion: 'Move 25,000 kg in a single session',
    blurb: 'Twenty-five tonnes between warm-up and shower.',
    unit: 'kg',
    target: 25_000,
    measure: (s) => s.biggestSessionKg,
  }),
  def({
    id: 'week-40k',
    name: 'Heavy Week',
    category: 'volume',
    rarity: 'rare',
    icon: Gauge,
    criterion: 'Move 40,000 kg inside one week',
    blurb: 'Forty tonnes in seven days.',
    unit: 'kg',
    target: 40_000,
    measure: (s) => s.bestWeekVolumeKg,
  }),
  def({
    id: 'reps-10k',
    name: 'Ten Thousand Reps',
    category: 'volume',
    rarity: 'uncommon',
    icon: Repeat,
    criterion: 'Complete 10,000 working reps',
    blurb: 'Ten thousand reps that counted.',
    unit: 'count',
    target: 10_000,
    measure: (s) => s.reps,
  }),
  def({
    id: 'reps-50k',
    name: 'Fifty Thousand Reps',
    category: 'volume',
    rarity: 'epic',
    icon: Atom,
    criterion: 'Complete 50,000 working reps',
    blurb: 'Fifty thousand reps. Every one of them logged.',
    unit: 'count',
    target: 50_000,
    measure: (s) => s.reps,
  }),
  def({
    id: 'sets-2k',
    name: 'Two Thousand Sets',
    category: 'volume',
    rarity: 'rare',
    icon: Boxes,
    criterion: 'Complete 2,000 working sets',
    blurb: 'Two thousand sets taken to the tick.',
    unit: 'count',
    target: 2_000,
    measure: (s) => s.sets,
  }),
  def({
    id: 'sets-10k',
    name: 'Ten Thousand Sets',
    category: 'volume',
    rarity: 'legendary',
    icon: Grip,
    criterion: 'Complete 10,000 working sets',
    blurb: 'Ten thousand sets. A career.',
    unit: 'count',
    target: 10_000,
    measure: (s) => s.sets,
  }),
  def({
    id: 'hours-100',
    name: 'Hundred Hours',
    category: 'volume',
    rarity: 'rare',
    icon: Hourglass,
    criterion: 'Spend 100 hours training',
    blurb: 'A hundred hours under load.',
    unit: 'hours',
    target: 100,
    measure: (s) => s.hours,
  }),
  def({
    id: 'hours-500',
    name: 'Five Hundred Hours',
    category: 'volume',
    rarity: 'legendary',
    icon: Clock,
    criterion: 'Spend 500 hours training',
    blurb: 'Five hundred hours. Three months of working days.',
    unit: 'hours',
    target: 500,
    measure: (s) => s.hours,
  }),
  def({
    id: 'session-2h',
    name: 'Long Haul',
    category: 'volume',
    rarity: 'uncommon',
    icon: Timer,
    criterion: 'Train for 2 hours in a single session',
    blurb: 'Two hours, start to finish, in one session.',
    unit: 'hours',
    target: 2,
    measure: (s) => s.longestSessionSec / 3600,
  }),

  // ------------------------------------------------------------------- strength
  def({
    id: 'bench-bw',
    name: 'Bodyweight Bench',
    category: 'strength',
    rarity: 'uncommon',
    icon: Weight,
    criterion: 'Estimated bench 1RM at 1.0× bodyweight',
    blurb: 'You bench what you weigh.',
    unit: 'ratio',
    target: 1,
    measure: (s) => s.benchRatio,
  }),
  def({
    id: 'bench-1-5',
    name: 'Bench and a Half',
    category: 'strength',
    rarity: 'epic',
    icon: Medal,
    criterion: 'Estimated bench 1RM at 1.5× bodyweight',
    blurb: 'One and a half times bodyweight off the chest.',
    unit: 'ratio',
    target: 1.5,
    measure: (s) => s.benchRatio,
  }),
  def({
    id: 'squat-1-5',
    name: 'Squat Standard',
    category: 'strength',
    rarity: 'uncommon',
    icon: Anchor,
    criterion: 'Estimated squat 1RM at 1.5× bodyweight',
    blurb: 'One and a half times bodyweight on your back.',
    unit: 'ratio',
    target: 1.5,
    measure: (s) => s.squatRatio,
  }),
  def({
    id: 'squat-2',
    name: 'Double Bodyweight Squat',
    category: 'strength',
    rarity: 'epic',
    icon: Gem,
    criterion: 'Estimated squat 1RM at 2.0× bodyweight',
    blurb: 'Twice your bodyweight, below parallel.',
    unit: 'ratio',
    target: 2,
    measure: (s) => s.squatRatio,
  }),
  def({
    id: 'dead-2',
    name: 'Double Bodyweight Pull',
    category: 'strength',
    rarity: 'rare',
    icon: Magnet,
    criterion: 'Estimated deadlift 1RM at 2.0× bodyweight',
    blurb: 'Twice bodyweight off the floor.',
    unit: 'ratio',
    target: 2,
    measure: (s) => s.deadliftRatio,
  }),
  def({
    id: 'dead-2-5',
    name: 'Elite Pull',
    category: 'strength',
    rarity: 'legendary',
    icon: Skull,
    criterion: 'Estimated deadlift 1RM at 2.5× bodyweight',
    blurb: 'Two and a half times bodyweight. Competition territory.',
    unit: 'ratio',
    target: 2.5,
    measure: (s) => s.deadliftRatio,
  }),
  def({
    id: 'press-075',
    name: 'Strong Overhead',
    category: 'strength',
    rarity: 'rare',
    icon: TrendingUp,
    criterion: 'Estimated overhead press 1RM at 0.75× bodyweight',
    blurb: 'Three quarters of bodyweight, locked out overhead.',
    unit: 'ratio',
    target: 0.75,
    measure: (s) => s.pressRatio,
  }),
  def({
    id: 'three-plates',
    name: 'Three Plates',
    category: 'strength',
    rarity: 'uncommon',
    icon: Target,
    criterion: 'Estimated deadlift 1RM of 140 kg',
    blurb: 'Three plates a side on a 20 kg bar.',
    unit: 'kg',
    target: 140,
    measure: (s) => s.deadliftKg,
  }),
  def({
    id: 'four-plates',
    name: 'Four Plates',
    category: 'strength',
    rarity: 'rare',
    icon: Radar,
    criterion: 'Estimated deadlift 1RM of 180 kg',
    blurb: 'Four plates a side. The bar bends now.',
    unit: 'kg',
    target: 180,
    measure: (s) => s.deadliftKg,
  }),
  def({
    id: 'thousand-pound',
    name: '1,000 lb Club',
    category: 'strength',
    rarity: 'epic',
    icon: Award,
    criterion: 'Bench + squat + deadlift estimated 1RMs reach 453.6 kg',
    blurb: 'A thousand pounds across the three lifts.',
    unit: 'kg',
    target: 453.6,
    measure: (s) => s.powerliftingTotalKg,
  }),
  def({
    id: 'total-500',
    name: 'Half-Tonne Total',
    category: 'strength',
    rarity: 'legendary',
    icon: Sword,
    criterion: 'Bench + squat + deadlift estimated 1RMs reach 500 kg',
    blurb: 'Half a tonne across the three lifts.',
    unit: 'kg',
    target: 500,
    measure: (s) => s.powerliftingTotalKg,
  }),
  def({
    id: 'heaviest-100',
    name: 'Triple Digits',
    category: 'strength',
    rarity: 'uncommon',
    icon: Bone,
    criterion: 'Complete a working set at 100 kg or more',
    blurb: 'A hundred kilograms on a working set.',
    unit: 'kg',
    target: 100,
    measure: (s) => s.heaviestSetKg,
  }),
  def({
    id: 'heaviest-180',
    name: 'Heavy Metal',
    category: 'strength',
    rarity: 'rare',
    icon: Hammer,
    criterion: 'Complete a working set at 180 kg or more',
    blurb: 'A hundred and eighty on a working set, not a single.',
    unit: 'kg',
    target: 180,
    measure: (s) => s.heaviestSetKg,
  }),
  def({
    id: 'prs-10',
    name: 'First Ten Records',
    category: 'strength',
    rarity: 'common',
    icon: Star,
    criterion: 'Set 10 personal records',
    blurb: 'Ten times you beat your old best.',
    unit: 'count',
    target: 10,
    measure: (s) => s.prs,
  }),
  def({
    id: 'prs-50',
    name: 'Record Hunter',
    category: 'strength',
    rarity: 'uncommon',
    icon: Sparkles,
    criterion: 'Set 50 personal records',
    blurb: 'Fifty personal records.',
    unit: 'count',
    target: 50,
    measure: (s) => s.prs,
  }),
  def({
    id: 'prs-150',
    name: 'Record Machine',
    category: 'strength',
    rarity: 'rare',
    icon: PartyPopper,
    criterion: 'Set 150 personal records',
    blurb: 'A hundred and fifty records broken.',
    unit: 'count',
    target: 150,
    measure: (s) => s.prs,
  }),

  // -------------------------------------------------------------------- variety
  def({
    id: 'moves-20',
    name: 'Twenty Movements',
    category: 'variety',
    rarity: 'common',
    icon: Compass,
    criterion: 'Log 20 different exercises',
    blurb: 'Twenty different movements in the log.',
    unit: 'count',
    target: 20,
    measure: (s) => s.distinctExercises,
  }),
  def({
    id: 'moves-40',
    name: 'Forty Movements',
    category: 'variety',
    rarity: 'rare',
    icon: Telescope,
    criterion: 'Log 40 different exercises',
    blurb: 'Forty different movements. You have tried most of the room.',
    unit: 'count',
    target: 40,
    measure: (s) => s.distinctExercises,
  }),
  def({
    id: 'muscles-12',
    name: 'Full Coverage',
    category: 'variety',
    rarity: 'uncommon',
    icon: Orbit,
    criterion: 'Train 12 different muscle groups',
    blurb: 'Twelve muscle groups trained. No obvious holes.',
    unit: 'count',
    target: 12,
    measure: (s) => s.distinctMuscles,
  }),
  def({
    id: 'muscles-all',
    name: 'Complete Map',
    category: 'variety',
    rarity: 'epic',
    icon: Flag,
    criterion: 'Train every muscle group in the catalogue',
    blurb: 'Every muscle group in the catalogue has been trained.',
    unit: 'count',
    target: (s) => s.muscleGroupsTotal,
    measure: (s) => s.distinctMuscles,
  }),
  def({
    id: 'legs-200',
    name: 'Leg Day Believer',
    category: 'variety',
    rarity: 'uncommon',
    icon: Bike,
    criterion: 'Complete 200 sets of quad, hamstring, glute or calf work',
    blurb: 'Two hundred leg sets. You did not skip it.',
    unit: 'count',
    target: 200,
    measure: (s) => s.legSets,
  }),
  def({
    id: 'back-200',
    name: 'Pull Focus',
    category: 'variety',
    rarity: 'uncommon',
    icon: Wrench,
    criterion: 'Complete 200 sets of back work',
    blurb: 'Two hundred sets of pulling.',
    unit: 'count',
    target: 200,
    measure: (s) => s.backSets,
  }),
  def({
    id: 'specialist-100',
    name: 'Specialist',
    category: 'variety',
    rarity: 'rare',
    icon: BookOpen,
    criterion: 'Perform one exercise in 100 different sessions',
    blurb: 'A hundred sessions of the same movement. That is how it gets good.',
    unit: 'count',
    target: 100,
    measure: (s) => s.favouriteExercise?.sessions ?? 0,
  }),

  // ------------------------------------------------------------------ milestone
  def({
    id: 'age-100',
    name: 'Hundred Days In',
    category: 'milestone',
    rarity: 'common',
    icon: Flag,
    criterion: '100 days since your first logged workout',
    blurb: 'A hundred days since the first entry in this log.',
    unit: 'count',
    target: 100,
    measure: (s) => s.daysSinceFirst,
  }),
  def({
    id: 'age-365',
    name: 'One Year In',
    category: 'milestone',
    rarity: 'rare',
    icon: Cake,
    criterion: '365 days since your first logged workout',
    blurb: 'A year of history in one log.',
    unit: 'count',
    target: 365,
    measure: (s) => s.daysSinceFirst,
  }),
  def({
    id: 'age-730',
    name: 'Two Years In',
    category: 'milestone',
    rarity: 'epic',
    icon: Milestone,
    criterion: '730 days since your first logged workout',
    blurb: 'Two years of training, all of it still here.',
    unit: 'count',
    target: 730,
    measure: (s) => s.daysSinceFirst,
  }),
  def({
    id: 'weigh-25',
    name: 'On the Scale',
    category: 'milestone',
    rarity: 'common',
    icon: Scale,
    criterion: 'Log 25 bodyweight entries',
    blurb: 'Twenty-five weigh-ins. Enough for a real trend line.',
    unit: 'count',
    target: 25,
    measure: (s) => s.weighIns,
  }),
  def({
    id: 'weigh-100',
    name: 'Measured',
    category: 'milestone',
    rarity: 'rare',
    icon: Ruler,
    criterion: 'Log 100 bodyweight entries',
    blurb: 'A hundred weigh-ins. The noise has nowhere to hide.',
    unit: 'count',
    target: 100,
    measure: (s) => s.weighIns,
  }),
];

export type EvaluatedBadge = {
  def: BadgeDef;
  value: number;
  target: number;
  earned: boolean;
  /** 0–1. */
  progress: number;
  /** False for one-shot criteria where a bar would just read 0% or 100%. */
  countable: boolean;
};

export function evaluateBadges(stats: ProfileStats): EvaluatedBadge[] {
  const out: EvaluatedBadge[] = [];
  for (const d of BADGES) {
    const target = typeof d.target === 'function' ? d.target(stats) : d.target;
    const value = d.measure(stats);
    const safeTarget = target > 0 ? target : 1;
    out.push({
      def: d,
      value,
      target,
      earned: value >= target && target > 0,
      progress: Math.max(0, Math.min(1, value / safeTarget)),
      countable: target > 1 || d.unit === 'ratio',
    });
  }
  // Earned first, rarest at the top. Then the locked ones ordered by how close
  // they are, so the next thing to chase is always at the front.
  out.sort((a, b) => {
    if (a.earned !== b.earned) return a.earned ? -1 : 1;
    if (a.earned) {
      const r = RARITY_ORDER[b.def.rarity] - RARITY_ORDER[a.def.rarity];
      if (r !== 0) return r;
      return a.def.name.localeCompare(b.def.name);
    }
    if (b.progress !== a.progress) return b.progress - a.progress;
    return RARITY_ORDER[a.def.rarity] - RARITY_ORDER[b.def.rarity];
  });
  return out;
}

/** "34 / 100", "182 / 250 kg", "1.24 / 1.50×". */
export function progressLabel(b: EvaluatedBadge): string {
  const { unit } = b.def;
  if (unit === 'ratio') return `${b.value.toFixed(2)} / ${b.target.toFixed(2)}×`;
  if (unit === 'hours') return `${trim(b.value)} / ${trim(b.target)} h`;
  const value = Math.floor(b.value).toLocaleString('en-US');
  const target = Math.round(b.target).toLocaleString('en-US');
  return unit === 'kg' ? `${value} / ${target} kg` : `${value} / ${target}`;
}

function trim(n: number): string {
  return Number.isInteger(n) ? `${n}` : n.toFixed(1);
}
