/**
 * Volume equivalents catalogue — real-world masses used by the Finish screen.
 *
 * Source: docs/research/stronger-2-0-volume-equivalents-system-finish-scre.md,
 * "PART 2 - The catalogue". Every mass is transcribed exactly from that brief,
 * which carries a citation per entry; none are rounded for tidiness and none
 * were invented here.
 *
 * Units: every `massKg` is KILOGRAMS, the canonical storage unit of the app.
 * Comparison counts are always computed from kg; display unit conversion happens
 * in the render layer and never touches these numbers.
 *
 * Pure TypeScript: no react / react-native / expo imports, runs under plain node.
 */

/** Broad family of a comparison object. Used to keep the two or three shown picks different. */
export type EquivCategory =
  | 'everyday'
  | 'gym'
  | 'animal'
  | 'vehicle'
  | 'aircraft'
  | 'marine'
  | 'space'
  | 'structure'
  | 'industrial'
  | 'legend';

/**
 * How firm the mass is.
 * - `verified`: a single published figure from the cited primary source (NASA, NPS, a spec sheet).
 * - `representative`: a typical value for something that genuinely varies (a fire engine, a sofa).
 * - `estimate`: a live scientific estimate with a published range (T. rex, Argentinosaurus).
 *
 * The UI should hedge copy ("about 19 tonnes") for anything that is not `verified`.
 */
export type Confidence = 'verified' | 'representative' | 'estimate';

/** One comparable real-world object. `massKg` is kilograms, always. */
export interface MassEquivalent {
  /** Stable slug. Persisted on the workout record, so it must never be regenerated or reordered. */
  readonly id: string;
  /** Bare noun, e.g. "African elephant". */
  readonly name: string;
  /** Article form for the count-of-one case, e.g. "an African elephant". */
  readonly singular: string;
  /** Plural form, e.g. "African elephants". */
  readonly plural: string;
  /** Mass in KILOGRAMS. */
  readonly massKg: number;
  readonly category: EquivCategory;
  /** Fallback glyph. The icon sheet is preferred wherever it has a matching key. */
  readonly emoji: string;
  /** Icon hint — a lucide-style key for the house icon sheet. */
  readonly icon: string;
  /** 0..1 — how likely the user has physically stood next to one. */
  readonly relatability: number;
  /** 0..1 — how good it sounds said out loud. */
  readonly spectacle: number;
  /** Optional one-line fact, <= 90 chars, shown at most once per screen. */
  readonly fun?: string;
  /** Where the mass came from. */
  readonly source: string;
  readonly sourceUrl: string;
  readonly confidence: Confidence;
  /**
   * Legend-tier: too heavy to ever yield a sane per-session count, so it is excluded
   * from the finish-screen picker and drives the lifetime milestone bar instead.
   */
  readonly milestoneOnly?: boolean;
}

/**
 * The full catalogue: 139 entries, 1 kg to 5,900,000,000 kg, sorted ascending by mass.
 * Ordering is presentation only — identity is the `id` slug, never the array index.
 */
export const MASS_EQUIVALENTS: readonly MassEquivalent[] = [
  {
    id: 'sugar-bag',
    name: 'bag of sugar',
    singular: 'a bag of sugar',
    plural: 'bags of sugar',
    massKg: 1,
    category: 'everyday',
    emoji: '🍚',
    icon: 'package',
    relatability: 1,
    spectacle: 0.05,
    fun: 'The unit every British kitchen thinks in.',
    source: 'Standard retail pack size',
    sourceUrl: 'https://en.wikipedia.org/wiki/Sugar',
    confidence: 'verified',
  },
  {
    id: 'pineapple',
    name: 'pineapple',
    singular: 'a pineapple',
    plural: 'pineapples',
    massKg: 1.1,
    category: 'everyday',
    emoji: '🍍',
    icon: 'apple',
    relatability: 0.95,
    spectacle: 0.05,
    source: 'USDA FoodData Central, whole pineapple 905-1,500 g',
    sourceUrl: 'https://fdc.nal.usda.gov/',
    confidence: 'representative',
  },
  {
    id: 'laptop',
    name: 'laptop',
    singular: 'a laptop',
    plural: 'laptops',
    massKg: 1.4,
    category: 'everyday',
    emoji: '💻',
    icon: 'laptop',
    relatability: 1,
    spectacle: 0.05,
    source: '14-inch class notebook, typical',
    sourceUrl: 'https://support.apple.com/en-us/111902',
    confidence: 'representative',
  },
  {
    id: 'chihuahua',
    name: 'chihuahua',
    singular: 'a chihuahua',
    plural: 'chihuahuas',
    massKg: 2.5,
    category: 'animal',
    emoji: '🐕',
    icon: 'dog',
    relatability: 0.8,
    spectacle: 0.1,
    fun: 'Small dog. Large opinions.',
    source: 'AKC breed standard, under 6 lb',
    sourceUrl: 'https://www.akc.org/dog-breeds/chihuahua/',
    confidence: 'verified',
  },
  {
    id: 'house-brick',
    name: 'house brick',
    singular: 'a house brick',
    plural: 'house bricks',
    massKg: 2.5,
    category: 'everyday',
    emoji: '🧱',
    icon: 'brick-wall',
    relatability: 0.9,
    spectacle: 0.1,
    source: 'Standard fired clay brick, 215x102.5x65 mm',
    sourceUrl: 'https://en.wikipedia.org/wiki/Brick',
    confidence: 'representative',
  },
  {
    id: 'newborn',
    name: 'newborn baby',
    singular: 'a newborn baby',
    plural: 'newborn babies',
    massKg: 3.4,
    category: 'everyday',
    emoji: '👶',
    icon: 'baby',
    relatability: 0.85,
    spectacle: 0.2,
    source: 'WHO average birth weight 3.2-3.5 kg',
    sourceUrl: 'https://www.who.int/',
    confidence: 'representative',
  },
  {
    id: 'milk-gallon',
    name: 'gallon of milk',
    singular: 'a gallon of milk',
    plural: 'gallons of milk',
    massKg: 3.9,
    category: 'everyday',
    emoji: '🥛',
    icon: 'milk',
    relatability: 0.95,
    spectacle: 0.05,
    source: 'US gallon of whole milk, density 1.03 kg/L',
    sourceUrl: 'https://www.usdairy.com/',
    confidence: 'verified',
  },
  {
    id: 'house-cat',
    name: 'house cat',
    singular: 'a house cat',
    plural: 'house cats',
    massKg: 4.5,
    category: 'animal',
    emoji: '🐈',
    icon: 'cat',
    relatability: 0.95,
    spectacle: 0.1,
    fun: 'Which, unlike your barbell, will not stay where you put it.',
    source: 'Adult domestic cat 3.6-5.4 kg',
    sourceUrl: 'https://www.petmd.com/cat/general-health/average-weight-cats',
    confidence: 'verified',
  },
  {
    id: 'bowling-ball',
    name: 'bowling ball',
    singular: 'a bowling ball',
    plural: 'bowling balls',
    massKg: 7.3,
    category: 'everyday',
    emoji: '🎳',
    icon: 'circle',
    relatability: 0.85,
    spectacle: 0.15,
    source: 'USBC maximum legal weight 16 lb',
    sourceUrl: 'https://bowl.com/rules',
    confidence: 'verified',
  },
  {
    id: 'road-bike',
    name: 'road bike',
    singular: 'a road bike',
    plural: 'road bikes',
    massKg: 8,
    category: 'vehicle',
    emoji: '🚲',
    icon: 'bike',
    relatability: 0.8,
    spectacle: 0.15,
    source: 'UCI minimum race weight 6.8 kg; consumer build ~8 kg',
    sourceUrl: 'https://www.uci.org/',
    confidence: 'representative',
  },
  {
    id: 'watermelon',
    name: 'watermelon',
    singular: 'a watermelon',
    plural: 'watermelons',
    massKg: 9,
    category: 'everyday',
    emoji: '🍉',
    icon: 'melon',
    relatability: 0.9,
    spectacle: 0.1,
    source: 'USDA, whole watermelon 8-10 kg typical',
    sourceUrl: 'https://fdc.nal.usda.gov/',
    confidence: 'representative',
  },
  {
    id: 'car-tyre',
    name: 'car tyre',
    singular: 'a car tyre',
    plural: 'car tyres',
    massKg: 11,
    category: 'vehicle',
    emoji: '🛞',
    icon: 'circle-dot',
    relatability: 0.8,
    spectacle: 0.1,
    source: '205/55R16 passenger tyre, 9-12 kg',
    sourceUrl: 'https://www.tyresafe.org/',
    confidence: 'representative',
  },
  {
    id: 'gold-bar',
    name: 'gold bar',
    singular: 'a gold bar',
    plural: 'gold bars',
    massKg: 12.4,
    category: 'everyday',
    emoji: '🪙',
    icon: 'gem',
    relatability: 0.3,
    spectacle: 0.6,
    fun: 'A Good Delivery bar. Roughly a million dollars of curl.',
    source: 'LBMA Good Delivery bar, 400 troy oz',
    sourceUrl: 'https://www.lbma.org.uk/good-delivery',
    confidence: 'verified',
  },
  {
    id: 'toddler',
    name: 'toddler',
    singular: 'a toddler',
    plural: 'toddlers',
    massKg: 12.5,
    category: 'everyday',
    emoji: '🧒',
    icon: 'baby',
    relatability: 0.85,
    spectacle: 0.15,
    source: 'WHO growth standards, 2-year-old median',
    sourceUrl: 'https://www.who.int/tools/child-growth-standards',
    confidence: 'representative',
  },
  {
    id: 'microwave',
    name: 'microwave',
    singular: 'a microwave',
    plural: 'microwaves',
    massKg: 15,
    category: 'everyday',
    emoji: '🔥',
    icon: 'microwave',
    relatability: 0.95,
    spectacle: 0.05,
    source: 'Countertop 25-30 L model, typical',
    sourceUrl: 'https://www.which.co.uk/reviews/microwaves',
    confidence: 'representative',
  },
  {
    id: 'kettlebell-16',
    name: 'competition kettlebell',
    singular: 'a competition kettlebell',
    plural: 'competition kettlebells',
    massKg: 16,
    category: 'gym',
    emoji: '🏋️',
    icon: 'dumbbell',
    relatability: 0.9,
    spectacle: 0.1,
    source: 'IUKL competition kettlebell, 16 kg class',
    sourceUrl: 'https://www.iukl.net/',
    confidence: 'verified',
  },
  {
    id: 'cinder-block',
    name: 'concrete block',
    singular: 'a concrete block',
    plural: 'concrete blocks',
    massKg: 17,
    category: 'everyday',
    emoji: '🧱',
    icon: 'box',
    relatability: 0.75,
    spectacle: 0.1,
    source: 'Standard 8x8x16 in CMU, 38 lb',
    sourceUrl: 'https://ncma.org/',
    confidence: 'representative',
  },
  {
    id: 'olympic-bar',
    name: 'Olympic barbell',
    singular: 'an Olympic barbell',
    plural: 'Olympic barbells',
    massKg: 20,
    category: 'gym',
    emoji: '🏋️',
    icon: 'dumbbell',
    relatability: 1,
    spectacle: 0.15,
    fun: 'The bar itself. The part everyone forgets to count.',
    source: 'IWF men\'s competition bar',
    sourceUrl: 'https://iwf.sport/',
    confidence: 'verified',
  },
  {
    id: 'bumper-plate',
    name: '25 kg plate',
    singular: 'a 25 kg plate',
    plural: '25 kg plates',
    massKg: 25,
    category: 'gym',
    emoji: '⚫',
    icon: 'circle',
    relatability: 1,
    spectacle: 0.1,
    source: 'IWF red competition disc',
    sourceUrl: 'https://iwf.sport/',
    confidence: 'verified',
  },
  {
    id: 'cement-bag',
    name: 'bag of cement',
    singular: 'a bag of cement',
    plural: 'bags of cement',
    massKg: 25,
    category: 'industrial',
    emoji: '🪣',
    icon: 'package',
    relatability: 0.7,
    spectacle: 0.15,
    source: 'EU standard 25 kg cement sack',
    sourceUrl: 'https://www.cembureau.eu/',
    confidence: 'verified',
  },
  {
    id: 'emperor-penguin',
    name: 'emperor penguin',
    singular: 'an emperor penguin',
    plural: 'emperor penguins',
    massKg: 30,
    category: 'animal',
    emoji: '🐧',
    icon: 'bird',
    relatability: 0.5,
    spectacle: 0.35,
    source: 'Aptenodytes forsteri, adult 22-45 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Emperor_penguin',
    confidence: 'representative',
  },
  {
    id: 'golden-retriever',
    name: 'golden retriever',
    singular: 'a golden retriever',
    plural: 'golden retrievers',
    massKg: 30,
    category: 'animal',
    emoji: '🐕',
    icon: 'dog',
    relatability: 0.9,
    spectacle: 0.15,
    source: 'AKC / breed standard 25-34 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Golden_Retriever',
    confidence: 'verified',
  },
  {
    id: 'dishwasher',
    name: 'dishwasher',
    singular: 'a dishwasher',
    plural: 'dishwashers',
    massKg: 35,
    category: 'everyday',
    emoji: '🍽️',
    icon: 'washing-machine',
    relatability: 0.9,
    spectacle: 0.05,
    source: 'Standard 24-inch built-in, 77 lb',
    sourceUrl: 'https://prudentreviews.com/dishwasher-weight/',
    confidence: 'representative',
  },
  {
    id: 'mattress',
    name: 'double mattress',
    singular: 'a double mattress',
    plural: 'double mattresses',
    massKg: 40,
    category: 'everyday',
    emoji: '🛏️',
    icon: 'bed',
    relatability: 0.9,
    spectacle: 0.05,
    source: 'Queen hybrid mattress, typical',
    sourceUrl: 'https://www.sleepfoundation.org/',
    confidence: 'representative',
  },
  {
    id: 'sofa',
    name: 'three-seat sofa',
    singular: 'a three-seat sofa',
    plural: 'three-seat sofas',
    massKg: 45,
    category: 'everyday',
    emoji: '🛋️',
    icon: 'sofa',
    relatability: 0.9,
    spectacle: 0.1,
    fun: 'And you thought moving one was hard.',
    source: 'Fabric three-seater, typical',
    sourceUrl: 'https://www.which.co.uk/',
    confidence: 'representative',
  },
  {
    id: 'cheetah',
    name: 'cheetah',
    singular: 'a cheetah',
    plural: 'cheetahs',
    massKg: 55,
    category: 'animal',
    emoji: '🐆',
    icon: 'cat',
    relatability: 0.4,
    spectacle: 0.45,
    source: 'Acinonyx jubatus, adult 46-72 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Cheetah',
    confidence: 'representative',
  },
  {
    id: 'average-human',
    name: 'adult human',
    singular: 'an adult human',
    plural: 'adult humans',
    massKg: 62,
    category: 'everyday',
    emoji: '🧍',
    icon: 'user',
    relatability: 1,
    spectacle: 0.3,
    fun: 'World average adult. Yes, we checked.',
    source: 'Walpole et al., The weight of nations, BMC Public Health 2012',
    sourceUrl: 'https://bmcpublichealth.biomedcentral.com/articles/10.1186/1471-2458-12-439',
    confidence: 'verified',
  },
  {
    id: 'kangaroo',
    name: 'red kangaroo',
    singular: 'a red kangaroo',
    plural: 'red kangaroos',
    massKg: 66,
    category: 'animal',
    emoji: '🦘',
    icon: 'rabbit',
    relatability: 0.4,
    spectacle: 0.4,
    source: 'Osphranter rufus, adult male 55-90 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Red_kangaroo',
    confidence: 'representative',
  },
  {
    id: 'fire-hydrant',
    name: 'fire hydrant',
    singular: 'a fire hydrant',
    plural: 'fire hydrants',
    massKg: 68,
    category: 'industrial',
    emoji: '🚒',
    icon: 'cylinder',
    relatability: 0.6,
    spectacle: 0.2,
    source: 'US dry-barrel hydrant upper section, typical',
    sourceUrl: 'https://www.muellercompany.com/',
    confidence: 'representative',
  },
  {
    id: 'beer-keg',
    name: 'full beer keg',
    singular: 'a full beer keg',
    plural: 'full beer kegs',
    massKg: 73.3,
    category: 'everyday',
    emoji: '🍺',
    icon: 'beer',
    relatability: 0.75,
    spectacle: 0.25,
    fun: 'A half-barrel. 161 lb of poor decisions.',
    source: 'US half-barrel keg, 161.5 lb full',
    sourceUrl: 'https://en.wikipedia.org/wiki/Keg',
    confidence: 'verified',
  },
  {
    id: 'washing-machine',
    name: 'washing machine',
    singular: 'a washing machine',
    plural: 'washing machines',
    massKg: 77,
    category: 'everyday',
    emoji: '🧺',
    icon: 'washing-machine',
    relatability: 0.95,
    spectacle: 0.15,
    source: 'Front-load domestic washer, ~170 lb average',
    sourceUrl: 'https://prudentreviews.com/washing-machine-dryer-weight/',
    confidence: 'verified',
  },
  {
    id: 'wild-boar',
    name: 'wild boar',
    singular: 'a wild boar',
    plural: 'wild boar',
    massKg: 90,
    category: 'animal',
    emoji: '🐗',
    icon: 'pig',
    relatability: 0.4,
    spectacle: 0.35,
    source: 'Sus scrofa, adult male 75-100 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Wild_boar',
    confidence: 'representative',
  },
  {
    id: 'us-adult-male',
    name: 'average American man',
    singular: 'an average American man',
    plural: 'average American men',
    massKg: 90.6,
    category: 'everyday',
    emoji: '🧍',
    icon: 'user',
    relatability: 0.95,
    spectacle: 0.25,
    source: 'CDC NHANES 2015-2018, men 20+, 199.8 lb',
    sourceUrl: 'https://www.cdc.gov/nchs/data/series/sr_03/sr03-046-508.pdf',
    confidence: 'verified',
  },
  {
    id: 'ostrich',
    name: 'ostrich',
    singular: 'an ostrich',
    plural: 'ostriches',
    massKg: 104,
    category: 'animal',
    emoji: '🦤',
    icon: 'bird',
    relatability: 0.4,
    spectacle: 0.4,
    fun: 'The heaviest bird alive, and it still can\'t fly.',
    source: 'Struthio camelus, adult 63-145 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Common_ostrich',
    confidence: 'representative',
  },
  {
    id: 'giant-panda',
    name: 'giant panda',
    singular: 'a giant panda',
    plural: 'giant pandas',
    massKg: 110,
    category: 'animal',
    emoji: '🐼',
    icon: 'panda',
    relatability: 0.5,
    spectacle: 0.45,
    source: 'Ailuropoda melanoleuca, adult male 100-115 kg',
    sourceUrl: 'https://www.worldwildlife.org/species/giant-panda',
    confidence: 'representative',
  },
  {
    id: 'refrigerator',
    name: 'fridge-freezer',
    singular: 'a fridge-freezer',
    plural: 'fridge-freezers',
    massKg: 136,
    category: 'everyday',
    emoji: '🧊',
    icon: 'refrigerator',
    relatability: 0.95,
    spectacle: 0.2,
    source: 'Full-size US refrigerator, just under 300 lb',
    sourceUrl: 'https://prudentreviews.com/refrigerator-weight/',
    confidence: 'representative',
  },
  {
    id: 'cast-iron-bath',
    name: 'cast-iron bathtub',
    singular: 'a cast-iron bathtub',
    plural: 'cast-iron bathtubs',
    massKg: 140,
    category: 'everyday',
    emoji: '🛁',
    icon: 'bath',
    relatability: 0.6,
    spectacle: 0.25,
    source: '5-ft enamelled cast-iron tub, empty',
    sourceUrl: 'https://www.kohler.com/',
    confidence: 'representative',
  },
  {
    id: 'blue-whale-heart',
    name: 'blue whale\'s heart',
    singular: 'a blue whale\'s heart',
    plural: 'blue whale hearts',
    massKg: 180,
    category: 'marine',
    emoji: '🫀',
    icon: 'heart',
    relatability: 0.2,
    spectacle: 0.8,
    fun: 'The largest heart on Earth. About the same as a concert piano\'s lid and legs.',
    source: 'NOAA Fisheries; ROM Trout River specimen, 180 kg',
    sourceUrl: 'https://www.fisheries.noaa.gov/feature-story/big-hearted-blue-whale',
    confidence: 'verified',
  },
  {
    id: 'silverback',
    name: 'silverback gorilla',
    singular: 'a silverback gorilla',
    plural: 'silverback gorillas',
    massKg: 180,
    category: 'animal',
    emoji: '🦍',
    icon: 'gorilla',
    relatability: 0.5,
    spectacle: 0.65,
    fun: 'Who, for the record, does not train legs either.',
    source: 'Adult male Gorilla, 135-227 kg, mean ~180 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Western_lowland_gorilla',
    confidence: 'representative',
  },
  {
    id: 'lion',
    name: 'lion',
    singular: 'a lion',
    plural: 'lions',
    massKg: 190,
    category: 'animal',
    emoji: '🦁',
    icon: 'cat',
    relatability: 0.5,
    spectacle: 0.6,
    source: 'Panthera leo, adult male mean 187.5 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Lion',
    confidence: 'representative',
  },
  {
    id: 'baby-grand',
    name: 'baby grand piano',
    singular: 'a baby grand piano',
    plural: 'baby grand pianos',
    massKg: 250,
    category: 'everyday',
    emoji: '🎹',
    icon: 'piano',
    relatability: 0.6,
    spectacle: 0.4,
    source: '5\'1" baby grand, 540-560 lb typical',
    sourceUrl: 'https://moversville.com/blog/how-much-does-a-piano-weigh-all-sizes',
    confidence: 'representative',
  },
  {
    id: 'vending-machine',
    name: 'vending machine',
    singular: 'a vending machine',
    plural: 'vending machines',
    massKg: 250,
    category: 'everyday',
    emoji: '🥤',
    icon: 'store',
    relatability: 0.8,
    spectacle: 0.25,
    source: 'Full-size glass-front beverage machine, loaded',
    sourceUrl: 'https://www.vendingmarketwatch.com/',
    confidence: 'representative',
  },
  {
    id: 'atm',
    name: 'cash machine',
    singular: 'a cash machine',
    plural: 'cash machines',
    massKg: 270,
    category: 'industrial',
    emoji: '🏧',
    icon: 'credit-card',
    relatability: 0.7,
    spectacle: 0.3,
    source: 'Through-the-wall ATM with safe, typical',
    sourceUrl: 'https://www.ncr.com/',
    confidence: 'representative',
  },
  {
    id: 'grizzly',
    name: 'grizzly bear',
    singular: 'a grizzly bear',
    plural: 'grizzly bears',
    massKg: 270,
    category: 'animal',
    emoji: '🐻',
    icon: 'bear',
    relatability: 0.5,
    spectacle: 0.6,
    source: 'Ursus arctos horribilis, adult male 180-360 kg',
    sourceUrl: 'https://www.nps.gov/yell/learn/nature/grizzlybear.htm',
    confidence: 'representative',
  },
  {
    id: 'upright-piano',
    name: 'upright piano',
    singular: 'an upright piano',
    plural: 'upright pianos',
    massKg: 295,
    category: 'everyday',
    emoji: '🎹',
    icon: 'piano',
    relatability: 0.65,
    spectacle: 0.35,
    source: 'Steinway Model K, 650 lb',
    sourceUrl: 'https://www.steinway.com/pianos/steinway/upright',
    confidence: 'verified',
  },
  {
    id: 'sea-lion',
    name: 'sea lion',
    singular: 'a sea lion',
    plural: 'sea lions',
    massKg: 300,
    category: 'marine',
    emoji: '🦭',
    icon: 'fish',
    relatability: 0.45,
    spectacle: 0.45,
    source: 'Zalophus californianus, adult male ~300 kg',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/california-sea-lion',
    confidence: 'representative',
  },
  {
    id: 'harley',
    name: 'Harley-Davidson',
    singular: 'a Harley-Davidson',
    plural: 'Harley-Davidsons',
    massKg: 361,
    category: 'vehicle',
    emoji: '🏍️',
    icon: 'bike',
    relatability: 0.7,
    spectacle: 0.45,
    source: 'Street Glide, 795.9 lb as shipped',
    sourceUrl: 'https://www.harley-davidson.com/',
    confidence: 'verified',
  },
  {
    id: 'polar-bear',
    name: 'polar bear',
    singular: 'a polar bear',
    plural: 'polar bears',
    massKg: 450,
    category: 'animal',
    emoji: '🐻‍❄️',
    icon: 'bear',
    relatability: 0.5,
    spectacle: 0.7,
    fun: 'The largest land carnivore on the planet.',
    source: 'Ursus maritimus, adult male 350-700 kg',
    sourceUrl: 'https://polarbearsinternational.org/',
    confidence: 'representative',
  },
  {
    id: 'concert-grand',
    name: 'concert grand piano',
    singular: 'a concert grand piano',
    plural: 'concert grand pianos',
    massKg: 480,
    category: 'everyday',
    emoji: '🎹',
    icon: 'piano',
    relatability: 0.6,
    spectacle: 0.5,
    fun: 'A Steinway Model D. Nine feet of very expensive ballast.',
    source: 'Steinway & Sons Model D, 990 lb',
    sourceUrl: 'https://www.steinway.com/pianos/steinway/grand/model-d',
    confidence: 'verified',
  },
  {
    id: 'racehorse',
    name: 'racehorse',
    singular: 'a racehorse',
    plural: 'racehorses',
    massKg: 500,
    category: 'animal',
    emoji: '🐎',
    icon: 'horse',
    relatability: 0.6,
    spectacle: 0.45,
    source: 'Thoroughbred, 1,000-1,200 lb',
    sourceUrl: 'https://en.wikipedia.org/wiki/Thoroughbred',
    confidence: 'representative',
  },
  {
    id: 'moose',
    name: 'moose',
    singular: 'a moose',
    plural: 'moose',
    massKg: 550,
    category: 'animal',
    emoji: '🫎',
    icon: 'deer',
    relatability: 0.45,
    spectacle: 0.55,
    source: 'Alces alces, adult bull 380-700 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Moose',
    confidence: 'representative',
  },
  {
    id: 'dairy-cow',
    name: 'dairy cow',
    singular: 'a dairy cow',
    plural: 'dairy cows',
    massKg: 725,
    category: 'animal',
    emoji: '🐄',
    icon: 'beef',
    relatability: 0.7,
    spectacle: 0.4,
    source: 'Mature Holstein Friesian, 680-770 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Holstein_Friesian',
    confidence: 'verified',
  },
  {
    id: 'f1-car',
    name: 'Formula 1 car',
    singular: 'a Formula 1 car',
    plural: 'Formula 1 cars',
    massKg: 798,
    category: 'vehicle',
    emoji: '🏎️',
    icon: 'car',
    relatability: 0.5,
    spectacle: 0.65,
    fun: 'Minimum legal weight, driver included.',
    source: 'FIA 2024 Technical Regulations, minimum mass 798 kg',
    sourceUrl: 'https://www.fia.com/regulation/category/110',
    confidence: 'verified',
  },
  {
    id: 'smart-car',
    name: 'Smart Fortwo',
    singular: 'a Smart Fortwo',
    plural: 'Smart Fortwos',
    massKg: 880,
    category: 'vehicle',
    emoji: '🚗',
    icon: 'car',
    relatability: 0.8,
    spectacle: 0.35,
    source: 'Curb weight 1,800-2,000 lb',
    sourceUrl: 'https://www.autopadre.com/vehicle-weight/smart-fortwo',
    confidence: 'representative',
  },
  {
    id: 'curiosity-rover',
    name: 'Curiosity rover',
    singular: 'the Curiosity rover',
    plural: 'Curiosity rovers',
    massKg: 899,
    category: 'space',
    emoji: '🛸',
    icon: 'rocket',
    relatability: 0.2,
    spectacle: 0.75,
    fun: 'Currently parked on Mars.',
    source: 'NASA MSL, dry mass 899 kg',
    sourceUrl: 'https://science.nasa.gov/mission/msl-curiosity/',
    confidence: 'verified',
  },
  {
    id: 'bison',
    name: 'American bison',
    singular: 'an American bison',
    plural: 'American bison',
    massKg: 900,
    category: 'animal',
    emoji: '🦬',
    icon: 'beef',
    relatability: 0.45,
    spectacle: 0.6,
    source: 'Bison bison, adult bull 700-1,000 kg',
    sourceUrl: 'https://www.nps.gov/yell/learn/nature/bison.htm',
    confidence: 'representative',
  },
  {
    id: 'shire-horse',
    name: 'shire horse',
    singular: 'a shire horse',
    plural: 'shire horses',
    massKg: 950,
    category: 'animal',
    emoji: '🐴',
    icon: 'horse',
    relatability: 0.4,
    spectacle: 0.55,
    source: 'Shire draught horse, 850-1,100 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Shire_horse',
    confidence: 'representative',
  },
  {
    id: 'saltwater-croc',
    name: 'saltwater crocodile',
    singular: 'a saltwater crocodile',
    plural: 'saltwater crocodiles',
    massKg: 1000,
    category: 'animal',
    emoji: '🐊',
    icon: 'fish',
    relatability: 0.4,
    spectacle: 0.7,
    fun: 'The largest living reptile. Bite force roughly 16,000 N.',
    source: 'Crocodylus porosus, large adult male ~1,000 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Saltwater_crocodile',
    confidence: 'representative',
  },
  {
    id: 'perseverance-rover',
    name: 'Perseverance rover',
    singular: 'the Perseverance rover',
    plural: 'Perseverance rovers',
    massKg: 1025,
    category: 'space',
    emoji: '🛸',
    icon: 'rocket',
    relatability: 0.2,
    spectacle: 0.75,
    source: 'NASA Mars 2020, dry mass 1,025 kg',
    sourceUrl: 'https://science.nasa.gov/mission/mars-2020-perseverance/',
    confidence: 'verified',
  },
  {
    id: 'great-white',
    name: 'great white shark',
    singular: 'a great white shark',
    plural: 'great white sharks',
    massKg: 1100,
    category: 'marine',
    emoji: '🦈',
    icon: 'fish',
    relatability: 0.4,
    spectacle: 0.8,
    source: 'Carcharodon carcharias, large female 680-1,100 kg',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/white-shark',
    confidence: 'representative',
  },
  {
    id: 'cessna-172',
    name: 'Cessna 172',
    singular: 'a Cessna 172',
    plural: 'Cessna 172s',
    massKg: 1157,
    category: 'aircraft',
    emoji: '🛩️',
    icon: 'plane',
    relatability: 0.4,
    spectacle: 0.5,
    fun: 'The most produced aircraft in history. Max takeoff weight.',
    source: 'Cessna 172S, MTOW 2,550 lb',
    sourceUrl: 'https://www.globalair.com/aircraft-specifications/cessna/cessna-172-sp-specifications/605',
    confidence: 'verified',
  },
  {
    id: 'giraffe',
    name: 'giraffe',
    singular: 'a giraffe',
    plural: 'giraffes',
    massKg: 1200,
    category: 'animal',
    emoji: '🦒',
    icon: 'deer',
    relatability: 0.55,
    spectacle: 0.65,
    source: 'Giraffa camelopardalis, adult male mean 1,192 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Giraffe',
    confidence: 'representative',
  },
  {
    id: 'walrus',
    name: 'walrus',
    singular: 'a walrus',
    plural: 'walruses',
    massKg: 1200,
    category: 'marine',
    emoji: '🦭',
    icon: 'fish',
    relatability: 0.35,
    spectacle: 0.6,
    source: 'Odobenus rosmarus, Pacific male 800-1,700 kg',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/pacific-walrus',
    confidence: 'representative',
  },
  {
    id: 'toyota-corolla',
    name: 'Toyota Corolla',
    singular: 'a Toyota Corolla',
    plural: 'Toyota Corollas',
    massKg: 1340,
    category: 'vehicle',
    emoji: '🚗',
    icon: 'car',
    relatability: 0.9,
    spectacle: 0.4,
    fun: 'The best-selling car ever made. Roughly 50 million of them.',
    source: 'Current-gen Corolla curb weight ~2,955 lb',
    sourceUrl: 'https://www.toyota.com/corolla/features/mileage_estimates/',
    confidence: 'representative',
  },
  {
    id: 'mini-cooper',
    name: 'Mini Cooper',
    singular: 'a Mini Cooper',
    plural: 'Mini Coopers',
    massKg: 1380,
    category: 'vehicle',
    emoji: '🚙',
    icon: 'car',
    relatability: 0.85,
    spectacle: 0.4,
    source: 'MINI Cooper 2-door, 3,014 lb curb',
    sourceUrl: 'https://www.autopadre.com/vehicle-weight/mini-cooper',
    confidence: 'verified',
  },
  {
    id: 'hippo',
    name: 'hippopotamus',
    singular: 'a hippopotamus',
    plural: 'hippopotamuses',
    massKg: 1500,
    category: 'animal',
    emoji: '🦛',
    icon: 'hippo',
    relatability: 0.5,
    spectacle: 0.7,
    source: 'Hippopotamus amphibius, adult male 1,500-1,800 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Hippopotamus',
    confidence: 'representative',
  },
  {
    id: 'narwhal',
    name: 'narwhal',
    singular: 'a narwhal',
    plural: 'narwhals',
    massKg: 1600,
    category: 'marine',
    emoji: '🐋',
    icon: 'fish',
    relatability: 0.25,
    spectacle: 0.65,
    source: 'Monodon monoceros, adult male 1,600 kg',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/narwhal',
    confidence: 'representative',
  },
  {
    id: 'tesla-model-3',
    name: 'Tesla Model 3',
    singular: 'a Tesla Model 3',
    plural: 'Tesla Model 3s',
    massKg: 1750,
    category: 'vehicle',
    emoji: '⚡',
    icon: 'car',
    relatability: 0.85,
    spectacle: 0.45,
    source: 'Curb weight 1,611-1,836 kg by variant',
    sourceUrl: 'https://en.wikipedia.org/wiki/Tesla_Model_3',
    confidence: 'verified',
  },
  {
    id: 'london-taxi',
    name: 'London black cab',
    singular: 'a London black cab',
    plural: 'London black cabs',
    massKg: 1800,
    category: 'vehicle',
    emoji: '🚕',
    icon: 'car',
    relatability: 0.65,
    spectacle: 0.45,
    source: 'LEVC TX, kerb weight ~2,150 kg; classic TX4 ~1,800 kg',
    sourceUrl: 'https://www.levc.com/',
    confidence: 'representative',
  },
  {
    id: 'ford-f150',
    name: 'Ford F-150',
    singular: 'a Ford F-150',
    plural: 'Ford F-150s',
    massKg: 2200,
    category: 'vehicle',
    emoji: '🛻',
    icon: 'truck',
    relatability: 0.8,
    spectacle: 0.5,
    source: 'Curb weight ~4,948 lb, heavier configurations higher',
    sourceUrl: 'https://www.ford.com/trucks/f150/',
    confidence: 'representative',
  },
  {
    id: 'container-20ft',
    name: 'empty shipping container',
    singular: 'an empty shipping container',
    plural: 'empty shipping containers',
    massKg: 2300,
    category: 'industrial',
    emoji: '📦',
    icon: 'container',
    relatability: 0.55,
    spectacle: 0.5,
    source: '20 ft ISO container tare, 5,070 lb',
    sourceUrl: 'https://www.icontainers.com/help/20-foot-container/',
    confidence: 'verified',
  },
  {
    id: 'white-rhino',
    name: 'white rhinoceros',
    singular: 'a white rhinoceros',
    plural: 'white rhinoceroses',
    massKg: 2300,
    category: 'animal',
    emoji: '🦏',
    icon: 'rhino',
    relatability: 0.5,
    spectacle: 0.7,
    source: 'Ceratotherium simum, adult male 2,000-2,400 kg',
    sourceUrl: 'https://www.worldwildlife.org/species/white-rhino',
    confidence: 'representative',
  },
  {
    id: 'pyramid-block',
    name: 'pyramid block',
    singular: 'a pyramid block',
    plural: 'pyramid blocks',
    massKg: 2500,
    category: 'structure',
    emoji: '🪨',
    icon: 'box',
    relatability: 0.3,
    spectacle: 0.7,
    fun: 'One of the 2.3 million limestone blocks in the Great Pyramid.',
    source: 'Great Pyramid average block, 2.5 tonnes',
    sourceUrl: 'https://www.sciencing.com/much-did-pyramids-weigh-7499289/',
    confidence: 'representative',
  },
  {
    id: 'blue-whale-tongue',
    name: 'blue whale\'s tongue',
    singular: 'a blue whale\'s tongue',
    plural: 'blue whale tongues',
    massKg: 2700,
    category: 'marine',
    emoji: '👅',
    icon: 'waves',
    relatability: 0.2,
    spectacle: 0.85,
    fun: 'Just the tongue. An entire elephant could stand on it.',
    source: 'NAMMCO, blue whale tongue ~2.7 tonnes',
    sourceUrl: 'https://nammco.no/blue-whale/',
    confidence: 'verified',
  },
  {
    id: 'airstream',
    name: 'Airstream trailer',
    singular: 'an Airstream trailer',
    plural: 'Airstream trailers',
    massKg: 3200,
    category: 'vehicle',
    emoji: '🚐',
    icon: 'caravan',
    relatability: 0.5,
    spectacle: 0.45,
    source: 'Airstream Classic 30RB, GVWR ~4,300 kg; dry ~3,200 kg',
    sourceUrl: 'https://www.airstream.com/',
    confidence: 'representative',
  },
  {
    id: 'container-40ft',
    name: '40-foot shipping container',
    singular: 'a 40-foot shipping container',
    plural: '40-foot shipping containers',
    massKg: 3750,
    category: 'industrial',
    emoji: '📦',
    icon: 'container',
    relatability: 0.5,
    spectacle: 0.55,
    source: '40 ft ISO container tare, 8,265 lb',
    sourceUrl: 'https://ship4wd.com/logistics-shipping/20ft-40ft-shipping-containers-specs',
    confidence: 'verified',
  },
  {
    id: 'zamboni',
    name: 'Zamboni',
    singular: 'a Zamboni',
    plural: 'Zambonis',
    massKg: 4000,
    category: 'vehicle',
    emoji: '🧊',
    icon: 'truck',
    relatability: 0.45,
    spectacle: 0.55,
    fun: 'The only vehicle with its own fan club.',
    source: 'Zamboni Model 552, operating weight ~4,000 kg',
    sourceUrl: 'https://zamboni.com/',
    confidence: 'representative',
  },
  {
    id: 'monster-truck',
    name: 'monster truck',
    singular: 'a monster truck',
    plural: 'monster trucks',
    massKg: 4500,
    category: 'vehicle',
    emoji: '🛻',
    icon: 'truck',
    relatability: 0.5,
    spectacle: 0.65,
    source: 'Monster Jam minimum competition weight 10,000 lb',
    sourceUrl: 'https://www.monsterjam.com/',
    confidence: 'verified',
  },
  {
    id: 'orca',
    name: 'orca',
    singular: 'an orca',
    plural: 'orcas',
    massKg: 5000,
    category: 'marine',
    emoji: '🐋',
    icon: 'fish',
    relatability: 0.45,
    spectacle: 0.8,
    source: 'Orcinus orca, adult male 3,600-5,400 kg',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/killer-whale',
    confidence: 'representative',
  },
  {
    id: 'african-elephant',
    name: 'African elephant',
    singular: 'an African elephant',
    plural: 'African elephants',
    massKg: 5300,
    category: 'animal',
    emoji: '🐘',
    icon: 'elephant',
    relatability: 0.6,
    spectacle: 0.85,
    fun: 'The largest land animal alive.',
    source: 'Loxodonta africana, adult male 4,500-6,100 kg',
    sourceUrl: 'https://animaldiversity.org/accounts/Loxodonta_africana/',
    confidence: 'verified',
  },
  {
    id: 'ambulance',
    name: 'ambulance',
    singular: 'an ambulance',
    plural: 'ambulances',
    massKg: 5380,
    category: 'vehicle',
    emoji: '🚑',
    icon: 'ambulance',
    relatability: 0.75,
    spectacle: 0.6,
    source: 'WAS 300 Mercedes Sprinter Type B, max total weight 5,380 kg',
    sourceUrl: 'https://www.was-vehicles.com/en/vehicles/was-300-panel-van-ambulances/was-300-transport-ambulance-mercedes-benz-sprinter-panel-van-type-b-zs',
    confidence: 'verified',
  },
  {
    id: 'woolly-mammoth',
    name: 'woolly mammoth',
    singular: 'a woolly mammoth',
    plural: 'woolly mammoths',
    massKg: 6000,
    category: 'animal',
    emoji: '🦣',
    icon: 'elephant',
    relatability: 0.35,
    spectacle: 0.85,
    source: 'Mammuthus primigenius, adult male 5,000-8,000 kg (estimate)',
    sourceUrl: 'https://en.wikipedia.org/wiki/Woolly_mammoth',
    confidence: 'estimate',
  },
  {
    id: 't-rex',
    name: 'Tyrannosaurus rex',
    singular: 'a Tyrannosaurus rex',
    plural: 'Tyrannosaurus rexes',
    massKg: 8400,
    category: 'animal',
    emoji: '🦖',
    icon: 'bone',
    relatability: 0.35,
    spectacle: 0.95,
    fun: 'Specifically \'Sue\', the most complete T. rex ever found.',
    source: 'Hutchinson et al. 2011, FMNH PR2081 body mass ~8.4 t',
    sourceUrl: 'https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0026037',
    confidence: 'estimate',
  },
  {
    id: 'f-16',
    name: 'F-16 fighter jet',
    singular: 'an F-16 fighter jet',
    plural: 'F-16 fighter jets',
    massKg: 8600,
    category: 'aircraft',
    emoji: '✈️',
    icon: 'plane',
    relatability: 0.35,
    spectacle: 0.8,
    source: 'F-16C Block 50 empty weight 19,100 lb with F110',
    sourceUrl: 'https://www.f-16.net/f-16_versions_article3.html',
    confidence: 'verified',
  },
  {
    id: 'black-hawk',
    name: 'Black Hawk helicopter',
    singular: 'a Black Hawk helicopter',
    plural: 'Black Hawk helicopters',
    massKg: 9980,
    category: 'aircraft',
    emoji: '🚁',
    icon: 'helicopter',
    relatability: 0.4,
    spectacle: 0.75,
    source: 'UH-60, maximum gross weight 22,000 lb',
    sourceUrl: 'https://www.lockheedmartin.com/en-us/products/sikorsky-uh-60m-black-hawk-helicopter.html',
    confidence: 'verified',
  },
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    singular: 'the Hubble Space Telescope',
    plural: 'Hubble Space Telescopes',
    massKg: 11110,
    category: 'space',
    emoji: '🔭',
    icon: 'telescope',
    relatability: 0.3,
    spectacle: 0.85,
    source: 'NASA/ESA fact sheet, launch mass 11,110 kg',
    sourceUrl: 'https://esahubble.org/about/general/fact_sheet/',
    confidence: 'verified',
  },
  {
    id: 'routemaster',
    name: 'London double-decker bus',
    singular: 'a London double-decker bus',
    plural: 'London double-decker buses',
    massKg: 12400,
    category: 'vehicle',
    emoji: '🚌',
    icon: 'bus',
    relatability: 0.7,
    spectacle: 0.65,
    fun: 'Unladen. Add 18 tonnes of commuters at rush hour.',
    source: 'New Routemaster unladen weight 12.4 tonnes, GVW 18.0 t',
    sourceUrl: 'https://www.london.gov.uk/who-we-are/what-london-assembly-does/questions-mayor/find-an-answer/new-bus-london-vehicle-weight-1',
    confidence: 'verified',
  },
  {
    id: 'crew-dragon',
    name: 'Crew Dragon capsule',
    singular: 'a Crew Dragon capsule',
    plural: 'Crew Dragon capsules',
    massKg: 12500,
    category: 'space',
    emoji: '🚀',
    icon: 'rocket',
    relatability: 0.3,
    spectacle: 0.8,
    source: 'SpaceX Crew Dragon launch mass ~12,519 kg',
    sourceUrl: 'https://www.spacex.com/vehicles/dragon/',
    confidence: 'representative',
  },
  {
    id: 'moai',
    name: 'Easter Island head',
    singular: 'an Easter Island head',
    plural: 'Easter Island heads',
    massKg: 13000,
    category: 'structure',
    emoji: '🗿',
    icon: 'landmark',
    relatability: 0.4,
    spectacle: 0.8,
    fun: 'Carved, then walked 18 km across the island. Nobody is fully sure how.',
    source: 'Moai average ~13 tonnes; largest 82 t',
    sourceUrl: 'https://www.nationalgeographic.com/history/article/everything-to-know-about-easter-islands-iconic-statues',
    confidence: 'representative',
  },
  {
    id: 'school-bus',
    name: 'school bus',
    singular: 'a school bus',
    plural: 'school buses',
    massKg: 13600,
    category: 'vehicle',
    emoji: '🚌',
    icon: 'bus',
    relatability: 0.75,
    spectacle: 0.6,
    source: 'Type C school bus GVWR 30,000 lb',
    sourceUrl: 'https://www.nhtsa.gov/road-safety/school-bus-safety',
    confidence: 'representative',
  },
  {
    id: 'big-ben-bell',
    name: 'Big Ben\'s Great Bell',
    singular: 'Big Ben\'s Great Bell',
    plural: 'Great Bells',
    massKg: 13700,
    category: 'structure',
    emoji: '🔔',
    icon: 'bell',
    relatability: 0.45,
    spectacle: 0.8,
    fun: 'Big Ben is the bell, not the tower. This is the hill we die on.',
    source: 'UK Parliament, Great Bell 13.7 tonnes',
    sourceUrl: 'https://www.parliament.uk/about/living-heritage/building/palace/big-ben/facts-figures/great-bell/',
    confidence: 'verified',
  },
  {
    id: 'lunar-module',
    name: 'Apollo Lunar Module',
    singular: 'an Apollo Lunar Module',
    plural: 'Apollo Lunar Modules',
    massKg: 15100,
    category: 'space',
    emoji: '🌕',
    icon: 'rocket',
    relatability: 0.3,
    spectacle: 0.9,
    fun: 'The whole thing that landed on the Moon.',
    source: 'LM Eagle, launch mass 15,102 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Lunar_Module_Eagle',
    confidence: 'verified',
  },
  {
    id: 'fire-engine',
    name: 'fire engine',
    singular: 'a fire engine',
    plural: 'fire engines',
    massKg: 19000,
    category: 'vehicle',
    emoji: '🚒',
    icon: 'truck',
    relatability: 0.7,
    spectacle: 0.65,
    source: 'Typical pumper GVWR 40,000-45,000 lb',
    sourceUrl: 'https://www.nfpa.org/codes-and-standards/nfpa-1901-standard-development/1901',
    confidence: 'representative',
  },
  {
    id: 'stonehenge-sarsen',
    name: 'Stonehenge sarsen',
    singular: 'a Stonehenge sarsen',
    plural: 'Stonehenge sarsens',
    massKg: 20000,
    category: 'structure',
    emoji: '🪨',
    icon: 'landmark',
    relatability: 0.35,
    spectacle: 0.85,
    fun: 'Dragged 25 km from West Woods around 2500 BC. Without a belt.',
    source: 'Nash et al., Science Advances 2020, typical upright ~20 t',
    sourceUrl: 'https://www.science.org/doi/10.1126/sciadv.abc0133',
    confidence: 'verified',
  },
  {
    id: 'humpback',
    name: 'humpback whale',
    singular: 'a humpback whale',
    plural: 'humpback whales',
    massKg: 30000,
    category: 'marine',
    emoji: '🐋',
    icon: 'fish',
    relatability: 0.45,
    spectacle: 0.85,
    source: 'Megaptera novaeangliae, adult ~30 tonnes',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/humpback-whale',
    confidence: 'representative',
  },
  {
    id: 'semi-truck',
    name: 'fully loaded semi truck',
    singular: 'a fully loaded semi truck',
    plural: 'fully loaded semi trucks',
    massKg: 36300,
    category: 'vehicle',
    emoji: '🚛',
    icon: 'truck',
    relatability: 0.7,
    spectacle: 0.7,
    source: 'US federal gross vehicle weight limit 80,000 lb',
    sourceUrl: 'https://ops.fhwa.dot.gov/freight/sw/overview/index.htm',
    confidence: 'verified',
  },
  {
    id: 'subway-car',
    name: 'subway car',
    singular: 'a subway car',
    plural: 'subway cars',
    massKg: 37000,
    category: 'vehicle',
    emoji: '🚇',
    icon: 'train',
    relatability: 0.6,
    spectacle: 0.65,
    source: 'NYC Subway R211, 82,000 lb',
    sourceUrl: 'https://en.wikipedia.org/wiki/R211_(New_York_City_Subway_car)',
    confidence: 'verified',
  },
  {
    id: 'sperm-whale',
    name: 'sperm whale',
    singular: 'a sperm whale',
    plural: 'sperm whales',
    massKg: 40000,
    category: 'marine',
    emoji: '🐳',
    icon: 'fish',
    relatability: 0.4,
    spectacle: 0.85,
    fun: 'The largest toothed predator that has ever lived.',
    source: 'Physeter macrocephalus, adult male ~40 tonnes',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/sperm-whale',
    confidence: 'representative',
  },
  {
    id: 'boeing-737-empty',
    name: 'empty Boeing 737',
    singular: 'an empty Boeing 737',
    plural: 'empty Boeing 737s',
    massKg: 41400,
    category: 'aircraft',
    emoji: '✈️',
    icon: 'plane',
    relatability: 0.6,
    spectacle: 0.75,
    source: '737-800 operating empty weight 41,413 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation',
    confidence: 'verified',
  },
  {
    id: 'abrams-tank',
    name: 'Abrams tank',
    singular: 'an Abrams tank',
    plural: 'Abrams tanks',
    massKg: 64600,
    category: 'vehicle',
    emoji: '🪖',
    icon: 'tank',
    relatability: 0.4,
    spectacle: 0.85,
    source: 'M1A2 SEPv2, 71.2 short tons',
    sourceUrl: 'https://en.wikipedia.org/wiki/M1_Abrams',
    confidence: 'verified',
  },
  {
    id: 'argentinosaurus',
    name: 'Argentinosaurus',
    singular: 'an Argentinosaurus',
    plural: 'Argentinosauruses',
    massKg: 70000,
    category: 'animal',
    emoji: '🦕',
    icon: 'bone',
    relatability: 0.25,
    spectacle: 0.95,
    fun: 'One of the heaviest land animals ever to exist.',
    source: 'Body mass estimates 65-80 tonnes',
    sourceUrl: 'https://en.wikipedia.org/wiki/Argentinosaurus',
    confidence: 'estimate',
  },
  {
    id: 'space-shuttle-orbiter',
    name: 'Space Shuttle orbiter',
    singular: 'a Space Shuttle orbiter',
    plural: 'Space Shuttle orbiters',
    massKg: 78844,
    category: 'space',
    emoji: '🚀',
    icon: 'rocket',
    relatability: 0.4,
    spectacle: 0.9,
    source: 'Orbiter empty mass 78,844 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Space_Shuttle_orbiter',
    confidence: 'verified',
  },
  {
    id: 'boeing-737-loaded',
    name: 'fully loaded Boeing 737',
    singular: 'a fully loaded Boeing 737',
    plural: 'fully loaded Boeing 737s',
    massKg: 79010,
    category: 'aircraft',
    emoji: '✈️',
    icon: 'plane',
    relatability: 0.65,
    spectacle: 0.8,
    source: '737-800 MTOW 79,010 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Boeing_737_Next_Generation',
    confidence: 'verified',
  },
  {
    id: 'mobile-crane',
    name: 'mobile crane',
    singular: 'a mobile crane',
    plural: 'mobile cranes',
    massKg: 108000,
    category: 'industrial',
    emoji: '🏗️',
    icon: 'crane',
    relatability: 0.4,
    spectacle: 0.7,
    source: 'Liebherr LTM 11200-9.1, total weight 108 t',
    sourceUrl: 'https://www.liebherr.com/en/int/products/mobile-and-crawler-cranes/mobile-cranes/ltm-mobile-cranes/ltm-mobile-cranes.html',
    confidence: 'verified',
  },
  {
    id: 'blue-whale',
    name: 'blue whale',
    singular: 'a blue whale',
    plural: 'blue whales',
    massKg: 110000,
    category: 'marine',
    emoji: '🐋',
    icon: 'whale',
    relatability: 0.55,
    spectacle: 1,
    fun: 'The largest animal that has ever existed. Including the dinosaurs.',
    source: 'NOAA Fisheries, average 110 tonnes (max ~190 t)',
    sourceUrl: 'https://www.fisheries.noaa.gov/species/blue-whale',
    confidence: 'verified',
  },
  {
    id: 'mir',
    name: 'Mir space station',
    singular: 'the Mir space station',
    plural: 'Mir space stations',
    massKg: 129700,
    category: 'space',
    emoji: '🛰️',
    icon: 'satellite',
    relatability: 0.25,
    spectacle: 0.85,
    source: 'Mir assembled mass 129,700 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Mir',
    confidence: 'verified',
  },
  {
    id: 'locomotive',
    name: 'diesel locomotive',
    singular: 'a diesel locomotive',
    plural: 'diesel locomotives',
    massKg: 185000,
    category: 'vehicle',
    emoji: '🚂',
    icon: 'train',
    relatability: 0.55,
    spectacle: 0.75,
    source: 'EMD SD70M, 407,000 lb',
    sourceUrl: 'https://www.progressrail.com/en/Segments/Locomotive.html',
    confidence: 'verified',
  },
  {
    id: 'concorde',
    name: 'Concorde',
    singular: 'a Concorde',
    plural: 'Concordes',
    massKg: 185070,
    category: 'aircraft',
    emoji: '✈️',
    icon: 'plane',
    relatability: 0.45,
    spectacle: 0.85,
    fun: 'New York to London in 2 hours 52 minutes. At max takeoff weight.',
    source: 'Concorde MTOW 185,070 kg',
    sourceUrl: 'http://www.concordesst.com/weight.html',
    confidence: 'verified',
  },
  {
    id: 'angel-of-the-north',
    name: 'Angel of the North',
    singular: 'the Angel of the North',
    plural: 'Angels of the North',
    massKg: 200000,
    category: 'structure',
    emoji: '🗿',
    icon: 'landmark',
    relatability: 0.3,
    spectacle: 0.7,
    source: 'Gateshead Council, 200 tonnes of weathering steel',
    sourceUrl: 'https://www.gateshead.gov.uk/article/3957/Angel-of-the-North',
    confidence: 'verified',
  },
  {
    id: 'statue-of-liberty',
    name: 'Statue of Liberty',
    singular: 'the Statue of Liberty',
    plural: 'Statues of Liberty',
    massKg: 204100,
    category: 'structure',
    emoji: '🗽',
    icon: 'landmark',
    relatability: 0.5,
    spectacle: 0.9,
    fun: 'Copper skin, iron skeleton, 225 tons of it.',
    source: 'NPS Statue Statistics, 450,000 lb total',
    sourceUrl: 'https://www.nps.gov/stli/learn/historyculture/statue-statistics.htm',
    confidence: 'verified',
  },
  {
    id: 'boeing-747-empty',
    name: 'empty Boeing 747',
    singular: 'an empty Boeing 747',
    plural: 'empty Boeing 747s',
    massKg: 220100,
    category: 'aircraft',
    emoji: '✈️',
    icon: 'plane',
    relatability: 0.6,
    spectacle: 0.85,
    source: '747-8 operating empty weight ~485,300 lb',
    sourceUrl: 'https://en.wikipedia.org/wiki/Boeing_747-8',
    confidence: 'verified',
  },
  {
    id: 'a380-empty',
    name: 'empty Airbus A380',
    singular: 'an empty Airbus A380',
    plural: 'empty Airbus A380s',
    massKg: 277000,
    category: 'aircraft',
    emoji: '🛫',
    icon: 'plane',
    relatability: 0.55,
    spectacle: 0.85,
    source: 'Airbus A380 OEW 277 tonnes',
    sourceUrl: 'https://www.airbus.com/sites/g/files/jlcbta136/files/2021-12/EN-Airbus-A380-Facts-and-Figures-December-2021_0.pdf',
    confidence: 'verified',
  },
  {
    id: 'iss',
    name: 'International Space Station',
    singular: 'the International Space Station',
    plural: 'International Space Stations',
    massKg: 419725,
    category: 'space',
    emoji: '🛰️',
    icon: 'satellite',
    relatability: 0.35,
    spectacle: 0.95,
    fun: 'Assembled 400 km up, one module at a time, over 12 years.',
    source: 'NASA, 925,335 lb without visiting vehicles',
    sourceUrl: 'https://www.nasa.gov/reference/international-space-station/',
    confidence: 'verified',
  },
  {
    id: 'boeing-747-loaded',
    name: 'fully loaded Boeing 747',
    singular: 'a fully loaded Boeing 747',
    plural: 'fully loaded Boeing 747s',
    massKg: 447700,
    category: 'aircraft',
    emoji: '✈️',
    icon: 'plane',
    relatability: 0.6,
    spectacle: 0.9,
    source: '747-8 MTOW 987,000 lb',
    sourceUrl: 'https://en.wikipedia.org/wiki/Boeing_747-8',
    confidence: 'verified',
  },
  {
    id: 'a380-loaded',
    name: 'fully loaded Airbus A380',
    singular: 'a fully loaded Airbus A380',
    plural: 'fully loaded Airbus A380s',
    massKg: 575000,
    category: 'aircraft',
    emoji: '🛫',
    icon: 'plane',
    relatability: 0.55,
    spectacle: 0.9,
    fun: 'The heaviest passenger aircraft ever mass-produced.',
    source: 'Airbus A380 MTOW 575 tonnes',
    sourceUrl: 'https://www.airbus.com/sites/g/files/jlcbta136/files/2021-12/EN-Airbus-A380-Facts-and-Figures-December-2021_0.pdf',
    confidence: 'verified',
  },
  {
    id: 'shuttle-srb',
    name: 'Space Shuttle booster',
    singular: 'a Space Shuttle booster',
    plural: 'Space Shuttle boosters',
    massKg: 590000,
    category: 'space',
    emoji: '🚀',
    icon: 'rocket',
    relatability: 0.25,
    spectacle: 0.9,
    source: 'Loaded SRB, 1,300,000 lb each',
    sourceUrl: 'https://www.nasa.gov/reference/space-shuttle-solid-rocket-boosters/',
    confidence: 'verified',
  },
  {
    id: 'cat-797f',
    name: 'CAT 797F haul truck',
    singular: 'a CAT 797F haul truck',
    plural: 'CAT 797F haul trucks',
    massKg: 623690,
    category: 'industrial',
    emoji: '🚜',
    icon: 'truck',
    relatability: 0.3,
    spectacle: 0.85,
    fun: 'Fully loaded. The tyres alone are four metres tall.',
    source: 'Caterpillar 797F gross machine operating weight 1,375,000 lb',
    sourceUrl: 'https://www.cat.com/en_US/products/new/equipment/off-highway-trucks/mining-trucks.html',
    confidence: 'verified',
  },
  {
    id: 'christ-the-redeemer',
    name: 'Christ the Redeemer',
    singular: 'Christ the Redeemer',
    plural: 'Christ the Redeemer statues',
    massKg: 635000,
    category: 'structure',
    emoji: '⛪',
    icon: 'landmark',
    relatability: 0.4,
    spectacle: 0.9,
    source: '635 metric tonnes, Corcovado, Rio de Janeiro',
    sourceUrl: 'https://en.wikipedia.org/wiki/Christ_the_Redeemer_(statue)',
    confidence: 'verified',
  },
  {
    id: 'an-225',
    name: 'Antonov An-225',
    singular: 'the Antonov An-225',
    plural: 'Antonov An-225s',
    massKg: 640000,
    category: 'aircraft',
    emoji: '🛫',
    icon: 'plane',
    relatability: 0.3,
    spectacle: 0.95,
    fun: 'The heaviest aircraft ever built. Only one was ever completed.',
    source: 'An-225 Mriya MTOW 640 tonnes',
    sourceUrl: 'https://en.wikipedia.org/wiki/Antonov_An-225_Mriya',
    confidence: 'verified',
  },
  {
    id: 'shuttle-external-tank',
    name: 'Shuttle external tank',
    singular: 'a Shuttle external tank',
    plural: 'Shuttle external tanks',
    massKg: 760000,
    category: 'space',
    emoji: '🚀',
    icon: 'rocket',
    relatability: 0.2,
    spectacle: 0.85,
    source: 'Loaded ET, 1,680,000 lb',
    sourceUrl: 'https://en.wikipedia.org/wiki/Space_Shuttle_external_tank',
    confidence: 'verified',
  },
  {
    id: 'london-eye',
    name: 'London Eye',
    singular: 'the London Eye',
    plural: 'London Eyes',
    massKg: 1700000,
    category: 'structure',
    emoji: '🎡',
    icon: 'ferris-wheel',
    relatability: 0.4,
    spectacle: 0.85,
    source: 'Wheel structure ~1,700 tonnes',
    sourceUrl: 'https://en.wikipedia.org/wiki/London_Eye',
    confidence: 'representative',
  },
  {
    id: 'shuttle-stack',
    name: 'Space Shuttle at launch',
    singular: 'a Space Shuttle at launch',
    plural: 'Space Shuttles at launch',
    massKg: 2030000,
    category: 'space',
    emoji: '🚀',
    icon: 'rocket',
    relatability: 0.3,
    spectacle: 0.95,
    fun: 'Orbiter, tank and both boosters, sitting on the pad.',
    source: 'Full stack launch mass ~4,470,000 lb',
    sourceUrl: 'https://www.nasa.gov/reference/space-shuttle-era/',
    confidence: 'verified',
  },
  {
    id: 'saturn-v',
    name: 'Saturn V rocket',
    singular: 'a Saturn V rocket',
    plural: 'Saturn V rockets',
    massKg: 2900000,
    category: 'space',
    emoji: '🚀',
    icon: 'rocket',
    relatability: 0.35,
    spectacle: 1,
    fun: 'Fully fuelled. Still the most powerful rocket ever flown to orbit with crew.',
    source: 'Saturn V launch mass 2,822,000-2,965,000 kg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Saturn_V',
    confidence: 'verified',
  },
  {
    id: 'atlas-detector',
    name: 'ATLAS detector',
    singular: 'the ATLAS detector',
    plural: 'ATLAS detectors',
    massKg: 7000000,
    category: 'structure',
    emoji: '⚛️',
    icon: 'atom',
    relatability: 0.15,
    spectacle: 0.85,
    fun: 'The thing at CERN that found the Higgs boson.',
    source: 'CERN, ATLAS weighs 7,000 tonnes',
    sourceUrl: 'https://home.cern/science/experiments/atlas',
    confidence: 'verified',
  },
  {
    id: 'eiffel-iron',
    name: 'Eiffel Tower\'s ironwork',
    singular: 'the Eiffel Tower\'s ironwork',
    plural: 'Eiffel Tower ironworks',
    massKg: 7300000,
    category: 'structure',
    emoji: '🗼',
    icon: 'landmark',
    relatability: 0.45,
    spectacle: 0.9,
    fun: '18,038 pieces of wrought iron and 2.5 million rivets.',
    source: 'SETE official figures, 7,300 tonnes of iron',
    sourceUrl: 'https://www.toureiffel.paris/en/the-monument/key-figures',
    confidence: 'verified',
  },
  {
    id: 'space-needle',
    name: 'Space Needle',
    singular: 'the Space Needle',
    plural: 'Space Needles',
    massKg: 8660000,
    category: 'structure',
    emoji: '🗼',
    icon: 'landmark',
    relatability: 0.35,
    spectacle: 0.8,
    source: '9,550 short tons',
    sourceUrl: 'https://www.spaceneedle.com/fun-facts',
    confidence: 'representative',
  },
  {
    id: 'eiffel-tower',
    name: 'Eiffel Tower',
    singular: 'the whole Eiffel Tower',
    plural: 'Eiffel Towers',
    massKg: 10100000,
    category: 'structure',
    emoji: '🗼',
    icon: 'landmark',
    relatability: 0.5,
    spectacle: 0.95,
    fun: 'Everything: iron, foundations, lifts, restaurants and all.',
    source: 'SETE official figures, 10,100 tonnes total',
    sourceUrl: 'https://www.toureiffel.paris/en/the-monument/key-figures',
    confidence: 'verified',
  },
  {
    id: 'tower-bridge',
    name: 'Tower Bridge',
    singular: 'Tower Bridge',
    plural: 'Tower Bridges',
    massKg: 11000000,
    category: 'structure',
    emoji: '🌉',
    icon: 'landmark',
    relatability: 0.4,
    spectacle: 0.85,
    source: '~11,000 tonnes of steel in the framework',
    sourceUrl: 'https://www.towerbridge.org.uk/discover/history',
    confidence: 'representative',
  },
  {
    id: 'bagger-288',
    name: 'Bagger 288',
    singular: 'the Bagger 288',
    plural: 'Bagger 288s',
    massKg: 13500000,
    category: 'industrial',
    emoji: '🏗️',
    icon: 'crane',
    relatability: 0.15,
    spectacle: 0.95,
    fun: 'A bucket-wheel excavator. For 20 years, the heaviest land vehicle on Earth.',
    source: '13,500 tonnes',
    sourceUrl: 'https://en.wikipedia.org/wiki/Bagger_288',
    confidence: 'verified',
  },
  {
    id: 'cms-detector',
    name: 'CMS detector',
    singular: 'the CMS detector',
    plural: 'CMS detectors',
    massKg: 14000000,
    category: 'structure',
    emoji: '⚛️',
    icon: 'atom',
    relatability: 0.15,
    spectacle: 0.85,
    fun: 'More iron than the Eiffel Tower, buried 100 m under the French border.',
    source: 'CERN, CMS weighs 14,000 tonnes',
    sourceUrl: 'https://home.cern/science/experiments/cms',
    confidence: 'verified',
  },
  {
    id: 'leaning-tower',
    name: 'Leaning Tower of Pisa',
    singular: 'the Leaning Tower of Pisa',
    plural: 'Leaning Towers of Pisa',
    massKg: 14500000,
    category: 'structure',
    emoji: '🏛️',
    icon: 'landmark',
    relatability: 0.45,
    spectacle: 0.85,
    source: '~14,500 tonnes',
    sourceUrl: 'https://en.wikipedia.org/wiki/Leaning_Tower_of_Pisa',
    confidence: 'representative',
  },
  {
    id: 'gateway-arch',
    name: 'Gateway Arch',
    singular: 'the Gateway Arch',
    plural: 'Gateway Arches',
    massKg: 15600000,
    category: 'structure',
    emoji: '🌉',
    icon: 'landmark',
    relatability: 0.3,
    spectacle: 0.85,
    source: 'NPS, 17,246 short tons',
    sourceUrl: 'https://www.nps.gov/jeff/learn/historyculture/gateway-arch-fact-sheet.htm',
    confidence: 'representative',
  },
  {
    id: 'titanic',
    name: 'Titanic',
    singular: 'the Titanic',
    plural: 'Titanics',
    massKg: 52310000,
    category: 'legend',
    emoji: '🚢',
    icon: 'ship',
    relatability: 0.5,
    spectacle: 1,
    fun: 'Full displacement. All 52,310 tonnes of it.',
    source: 'RMS Titanic displacement 52,310 tonnes',
    sourceUrl: 'https://en.wikipedia.org/wiki/Titanic',
    confidence: 'verified',
    milestoneOnly: true,
  },
  {
    id: 'sydney-harbour-bridge',
    name: 'Sydney Harbour Bridge',
    singular: 'the Sydney Harbour Bridge',
    plural: 'Sydney Harbour Bridges',
    massKg: 52800000,
    category: 'legend',
    emoji: '🌉',
    icon: 'landmark',
    relatability: 0.35,
    spectacle: 0.9,
    source: '52,800 tonnes of steel',
    sourceUrl: 'https://www.bridgeclimb.com/about/bridge-facts',
    confidence: 'representative',
    milestoneOnly: true,
  },
  {
    id: 'nimitz-carrier',
    name: 'aircraft carrier',
    singular: 'an aircraft carrier',
    plural: 'aircraft carriers',
    massKg: 100000000,
    category: 'legend',
    emoji: '⚓',
    icon: 'ship',
    relatability: 0.35,
    spectacle: 0.95,
    source: 'Nimitz-class full load displacement ~100,000 tonnes',
    sourceUrl: 'https://www.navy.mil/Resources/Fact-Files/',
    confidence: 'representative',
    milestoneOnly: true,
  },
  {
    id: 'ever-given',
    name: 'Ever Given',
    singular: 'the Ever Given',
    plural: 'Ever Givens',
    massKg: 199629000,
    category: 'legend',
    emoji: '🚢',
    icon: 'ship',
    relatability: 0.3,
    spectacle: 0.9,
    fun: 'The one that got stuck in the Suez Canal. Deadweight tonnage.',
    source: 'Ever Given DWT 199,629 t',
    sourceUrl: 'https://en.wikipedia.org/wiki/Ever_Given',
    confidence: 'verified',
    milestoneOnly: true,
  },
  {
    id: 'empire-state',
    name: 'Empire State Building',
    singular: 'the Empire State Building',
    plural: 'Empire State Buildings',
    massKg: 331000000,
    category: 'legend',
    emoji: '🏙️',
    icon: 'building',
    relatability: 0.45,
    spectacle: 0.95,
    source: '365,000 short tons',
    sourceUrl: 'https://www.esbnyc.com/about/facts-figures',
    confidence: 'representative',
    milestoneOnly: true,
  },
  {
    id: 'golden-gate',
    name: 'Golden Gate Bridge',
    singular: 'the Golden Gate Bridge',
    plural: 'Golden Gate Bridges',
    massKg: 804700000,
    category: 'legend',
    emoji: '🌉',
    icon: 'landmark',
    relatability: 0.4,
    spectacle: 0.95,
    source: '887,000 short tons including anchorages and approaches (post-1986)',
    sourceUrl: 'https://www.goldengate.org/bridge/history-research/statistics-data/',
    confidence: 'representative',
    milestoneOnly: true,
  },
  {
    id: 'great-pyramid',
    name: 'Great Pyramid of Giza',
    singular: 'the Great Pyramid of Giza',
    plural: 'Great Pyramids',
    massKg: 5900000000,
    category: 'legend',
    emoji: '🔺',
    icon: 'triangle',
    relatability: 0.4,
    spectacle: 1,
    fun: '2.3 million blocks. The heaviest thing humans built for 3,800 years.',
    source: '~5.9 million tonnes (estimates 5.7-6.5 Mt)',
    sourceUrl: 'https://www.sciencing.com/much-did-pyramids-weigh-7499289/',
    confidence: 'estimate',
    milestoneOnly: true,
  },
];

/** Mass above which an entry is treated as legend-tier, in kg (research PART 3, `nextMilestone`). */
export const MILESTONE_THRESHOLD_KG = 2e7;

/**
 * Entries the finish-screen picker may choose from: everything that is not legend-tier.
 * Sorted ascending by mass, same as the full catalogue.
 */
export const PICKABLE_EQUIVALENTS: readonly MassEquivalent[] = MASS_EQUIVALENTS.filter(
  (e) => !isMilestone(e),
);

/**
 * Legend-tier entries, ascending by mass. These power the lifetime progress line
 * ("3.1% of the Titanic"), never a per-session ratio.
 */
export const MILESTONE_EQUIVALENTS: readonly MassEquivalent[] = MASS_EQUIVALENTS.filter(isMilestone);

/** True when an entry is legend-tier: flagged `milestoneOnly`, or at/above 20,000 tonnes. */
export function isMilestone(entry: MassEquivalent): boolean {
  return entry.milestoneOnly === true || entry.massKg >= MILESTONE_THRESHOLD_KG;
}

const BY_ID: ReadonlyMap<string, MassEquivalent> = new Map(
  MASS_EQUIVALENTS.map((e) => [e.id, e]),
);

/**
 * Look up a catalogue entry by its stable slug.
 * Returns `undefined` for an id that is no longer in the catalogue — an old workout
 * can reference a retired entry, and the caller must render that gracefully.
 */
export function getEquivalent(id: string): MassEquivalent | undefined {
  return BY_ID.get(id);
}

/**
 * How many of `entry` weigh `totalKg`. Both inputs are kilograms.
 * Returns 0 for a non-positive or non-finite total, so an empty session never
 * produces a comparison at all.
 */
export function countOf(totalKg: number, entry: MassEquivalent): number {
  if (!Number.isFinite(totalKg) || totalKg <= 0) return 0;
  return totalKg / entry.massKg;
}
